title: <p align="center"> Vishnu Vivek </p>
logo: /assets/img/Vishnu Vivek.jpg
description: 
  <p align="center">
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with CHEORS India for data base team.
  Working in Pharma domain for 4 years.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
